# version: '3'
services:
  try-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: ".env"
    restart: "always"
    volumes:
      - ./logs:/app/logs
      - ./src:/app
