from fastapi import APIRouter, Depends, HTTPException
from typing import Generator
from sqlalchemy import select
from sqlalchemy.orm import Session

from src.models.tasks import Task as TaskORM
from src.schemas.tasks import Task as TaskSchema, TaskCreate
from src.database import SessionLocal
from src.logger import logger

router = APIRouter(
    prefix="/tasks",
    tags=["tasks"],
)

def get_db() -> Generator[Session, None, None]:
    """
    FastAPI dependency that provides a SQLAlchemy session for one request.

    Opens a session before the route runs and closes it afterward, so
    connections are not leaked.

    Yields:
        Session: Database session bound to this request.

    Example:
        Injected via ``Depends(get_db)`` on route parameters.
    """
    logger.info("Getting db")
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@router.get("/", response_model=list[TaskSchema])
def get_tasks(db: Session = Depends(get_db)) -> list[TaskORM]:
    """
        List every task row in the database.

        Args:
            db: Active SQLAlchemy session (injected).

        Returns:
            list[TaskORM]: All task rows; responses are serialized as ``TaskSchema``.

        Raises:
            None: Database errors propagate as 500 unless handled globally.
        """
    logger.info("Getting all tasks")
    return list(db.scalars(select(TaskORM)).all())

@router.get("/{task_id}", response_model=TaskSchema)
def get_task(task_id: int, db: Session = Depends(get_db)) -> TaskORM:
    """
    Return a single task by primary key.

    Args:
        task_id: Numeric primary key of the task.
        db: Active SQLAlchemy session (injected).

    Returns:
        TaskORM: The matching row, serialized per ``TaskSchema``.

    Raises:
        HTTPException: 404 if no task exists for ``task_id``.
    """
    logger.info(f"Getting task with ID {task_id}")
    task = db.scalars(select(TaskORM).where(TaskORM.id == task_id)).first()
    if not task:
        logger.error(f"Task with ID {task_id} not found")
        raise HTTPException(status_code=404, detail="Task not found")
    return task


@router.post("/", response_model=TaskSchema, tags=["tasks"])
def create_task(task_data: TaskCreate, db: Session = Depends(get_db)) -> TaskORM:
    """
    Persist a new task from validated input.

    Args:
        task_data: Payload with ``title``, ``description``, and ``completed``;
            must not include ``id`` (generated by the database).
        db: Active SQLAlchemy session (injected).

    Returns:
        TaskORM: Created entity including auto-generated ``id``.

    Raises:
        None: Validation errors return 422 from FastAPI before this runs.
    """
    logger.info("Creating new task")
    new_task = TaskORM(
        title=task_data.title,
        description=task_data.description,
        completed=task_data.completed,
    )

    db.add(new_task)
    db.commit()
    db.refresh(new_task)
    logger.info(f"Created new task with ID {new_task.id}")
    return new_task

@router.put("/tasks/{task_id}", response_model=TaskSchema, tags=["tasks"])
def update_task(task_id: int, task_data: TaskCreate, db: Session = Depends(get_db)) -> TaskORM:
    """
    Update a task by primary key.

    Args:
        task_id: Numeric primary key of the task to update.
        task_data: Payload with ``title``, ``description``, and ``completed``;
            must not include ``id`` (generated by the database).
        db: Active SQLAlchemy session (injected).

    Returns:
        TaskORM: Updated row; response is serialized as ``TaskSchema``.

    Raises:
        HTTPException: 404 if no task exists for ``task_id``.
    """
    logger.info(f"Updating task with ID {task_id}")
    task = db.scalars(select(TaskORM).where(TaskORM.id == task_id)).first()
    if not task:
        logger.error(f"Task with ID {task_id} not found")
        raise HTTPException(status_code=404, detail="Task not found")
    task.title = task_data.title
    task.description = task_data.description
    task.completed = task_data.completed
    db.commit()
    db.refresh(task)
    logger.info(f"Updated task with ID {task_id}")
    return task


@router.delete("/tasks/{task_id}", tags=["tasks"])
def delete_task(task_id: int, db: Session = Depends(get_db)) -> dict[str, str]:
    """
    Remove a task by primary key.

    Args:
        task_id: Numeric primary key of the task to delete.
        db: Active SQLAlchemy session (injected).

    Returns:
        dict: JSON body ``{"message": "Task <id> was deleted"}`` on success;
        HTTP status **200** with ``Content-Type: application/json``.

    Raises:
        HTTPException: 404 if no task exists for ``task_id``.
    """
    logger.info(f"Deleting task with ID {task_id}")
    task = db.scalars(select(TaskORM).where(TaskORM.id == task_id)).first()
    if not task:
        logger.error(f"Task with ID {task_id} not found")
        raise HTTPException(status_code=404, detail="Task not found")
    db.delete(task)
    db.commit()
    logger.info(f"Deleted task with ID {task_id}")
    return {"message": f"Task {task_id} was deleted"}