from fastapi import FastAPI, HTTPException, Depends
from sqlalchemy.orm import Session
from typing import List

import models
import schemas
from database import engine, SessionLocal

# Create database tables
models.Base.metadata.create_all(bind=engine)

app = FastAPI(title="Task Manager API")


# Dependency to get DB session
def get_db():
    """
    Yields a database session and ensures it's closed after the request.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@app.get("/tasks", response_model=List[schemas.Task])
def get_tasks(db: Session = Depends(get_db)):
    """
    Get all tasks from the database.
    Returns the full Task model (including ID).
    """
    return db.query(models.Task).all()


@app.get("/tasks/{task_id}", response_model=schemas.Task)
def get_task(task_id: int, db: Session = Depends(get_db)):
    """
    Get a single task by ID.
    """
    task = db.query(models.Task).filter(models.Task.id == task_id).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    return task


@app.post("/tasks", response_model=schemas.Task)
def create_task(task_data: schemas.TaskCreate, db: Session = Depends(get_db)):
    """
    Create a new task.
    Input: TaskCreate (title, description, completed) - No ID required.
    Output: Task (includes the auto-generated ID).
    """
    # Create SQLAlchemy model instance from Pydantic data
    new_task = models.Task(
        title=task_data.title,
        description=task_data.description,
        completed=task_data.completed
    )

    db.add(new_task)
    db.commit()
    db.refresh(new_task)  # This retrieves the ID generated by the DB
    return new_task